import {
  Conversation,
  ChatMessage,
  Review,
  Report,
  AppNotification,
} from '../types/index.js';

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'c-001',
    listingId: 'l-001',
    listingTitle: 'Phòng trọ gác lửng thoáng mát gần ĐH Duy Tân [MẪU - DEV]',
    tenantId: 'u-tenant-1',
    tenantName: 'Nguyễn Văn An (Người thuê)',
    landlordId: 'u-landlord-1',
    landlordName: 'Cô Lan (Chủ nhà)',
    lastMessagePreview: 'Dạ vâng, chiều mai 15h em ghé xem phòng nhé cô!',
    lastMessageAt: '2026-09-24T08:30:00Z',
    createdAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'c-002',
    listingId: 'l-002',
    listingTitle: 'Căn hộ mini ban công lộng gió gần biển Mỹ Khê [MẪU - DEV]',
    tenantId: 'u-tenant-1',
    tenantName: 'Nguyễn Văn An (Người thuê)',
    landlordId: 'u-landlord-2',
    landlordName: 'Anh Minh Căn Hộ',
    lastMessagePreview: 'Bạn add Zalo 0901234567 để mình gửi video phòng nha',
    lastMessageAt: '2026-09-24T09:15:00Z',
    createdAt: '2026-09-24T09:00:00Z',
  },
];

export const MOCK_MESSAGES: Record<string, ChatMessage[]> = {
  'c-001': [
    {
      id: 'm-001',
      conversationId: 'c-001',
      senderId: 'u-tenant-1',
      senderName: 'Nguyễn Văn An',
      content: 'Cháu chào cô Lan ạ, phòng trọ gác lửng trên đường Nguyễn Du này còn trống không cô?',
      isRead: true,
      createdAt: '2026-09-24T08:00:00Z',
    },
    {
      id: 'm-002',
      conversationId: 'c-001',
      senderId: 'u-landlord-1',
      senderName: 'Cô Lan (Chủ nhà)',
      content: 'Chào cháu, phòng vẫn còn nhé. Phòng có điều hòa, WC khép kín và gác lửng sạch sẽ lắm.',
      isRead: true,
      createdAt: '2026-09-24T08:05:00Z',
    },
    {
      id: 'm-003',
      conversationId: 'c-001',
      senderId: 'u-tenant-1',
      senderName: 'Nguyễn Văn An',
      content: 'Dạ tiền điện nước tính theo đồng hồ đúng như trên tin đăng đúng không ạ?',
      isRead: true,
      createdAt: '2026-09-24T08:10:00Z',
    },
    {
      id: 'm-004',
      conversationId: 'c-001',
      senderId: 'u-landlord-1',
      senderName: 'Cô Lan (Chủ nhà)',
      content: 'Đúng rồi cháu, điện có công tơ riêng từng phòng 3.500đ/kWh, nước sinh hoạt 60.000đ/người/tháng, để xe miễn phí.',
      isRead: true,
      createdAt: '2026-09-24T08:15:00Z',
    },
    {
      id: 'm-005',
      conversationId: 'c-001',
      senderId: 'u-tenant-1',
      senderName: 'Nguyễn Văn An',
      content: 'Dạ vâng, chiều mai 15h em ghé xem phòng nhé cô!',
      isRead: true,
      createdAt: '2026-09-24T08:30:00Z',
    },
  ],
  'c-002': [
    {
      id: 'm-010',
      conversationId: 'c-002',
      senderId: 'u-tenant-1',
      senderName: 'Nguyễn Văn An',
      content: 'Anh Minh ơi, căn hộ mini ở Hồ Nghinh còn không anh?',
      isRead: true,
      createdAt: '2026-09-24T09:00:00Z',
    },
    {
      id: 'm-011',
      conversationId: 'c-002',
      senderId: 'u-landlord-2',
      senderName: 'Anh Minh Căn Hộ',
      content: 'Bạn add Zalo 0901234567 để mình gửi video phòng nha',
      isRead: true,
      createdAt: '2026-09-24T09:15:00Z',
      detectedRisks: ['add zalo'],
    },
  ],
};

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r-001',
    listingId: 'l-001',
    tenantId: 'u-tenant-2',
    tenantName: 'Trần Thị Mai [MẪU - DEV]',
    rating: 5,
    content: 'Phòng sạch sẽ, an ninh tốt, cô chủ thân thiện dễ tính. Điện nước đúng chỉ số đồng hồ, không phát sinh chi phí vô lý.',
    status: 'approved',
    landlordResponse: 'Cảm ơn con nhé, chúc con học tập tốt!',
    createdAt: '2026-09-15T10:00:00Z',
    updatedAt: '2026-09-15T14:00:00Z',
  },
  {
    id: 'r-002',
    listingId: 'l-001',
    tenantId: 'u-tenant-3',
    tenantName: 'Lê Hoàng Nam [MẪU - DEV]',
    rating: 4,
    content: 'Khu vực yên tĩnh gần trường, chỗ để xe rộng rãi có camera. Điểm trừ nhỏ là ngõ hơi hẹp vào giờ cao điểm.',
    status: 'approved',
    landlordResponse: null,
    createdAt: '2026-09-18T16:20:00Z',
    updatedAt: '2026-09-18T16:20:00Z',
  },
  {
    id: 'r-003',
    listingId: 'l-002',
    tenantId: 'u-tenant-4',
    tenantName: 'Vũ Quốc Bảo [MẪU - DEV]',
    rating: 3,
    content: 'Phòng thoáng mát ban công view biển đẹp, tuy nhiên phí gửi xe và dịch vụ chung hơi cao hơn kỳ vọng.',
    status: 'pending',
    landlordResponse: null,
    createdAt: '2026-09-23T11:00:00Z',
    updatedAt: '2026-09-23T11:00:00Z',
  },
];

export const MOCK_REPORTS: Report[] = [
  {
    id: 'rep-001',
    reporterId: 'u-tenant-1',
    reporterName: 'Nguyễn Văn An [MẪU - DEV]',
    targetType: 'listing',
    targetId: 'l-003',
    targetTitle: 'Phòng trọ sinh viên giá rẻ gần ĐH Bách Khoa [MẪU - DEV]',
    reasonCategory: 'wrong_price',
    details: 'Tin đăng ghi tiền điện 2.000đ nhưng khi gọi điện chủ báo 4.500đ/kWh bắt buộc.',
    status: 'pending',
    createdAt: '2026-09-24T07:15:00Z',
  },
  {
    id: 'rep-002',
    reporterId: 'u-tenant-5',
    reporterName: 'Đặng Thảo Vy [MẪU - DEV]',
    targetType: 'message',
    targetId: 'm-999',
    targetTitle: 'Tin nhắn yêu cầu chuyển khoản',
    reasonCategory: 'deposit_scam',
    details: 'Đối tượng liên tục hối thúc chuyển cọc trước 1 triệu vào STK ngân hàng trước khi xem phòng.',
    status: 'pending',
    createdAt: '2026-09-23T18:40:00Z',
  },
  {
    id: 'rep-003',
    reporterId: 'u-tenant-2',
    reporterName: 'Trần Thị Mai [MẪU - DEV]',
    targetType: 'listing',
    targetId: 'l-998',
    targetTitle: 'Căn hộ chung cư ảo đường Điện Biên Phủ [MẪU - DEV]',
    reasonCategory: 'fake_listing',
    details: 'Ảnh lấy từ dự án ở TP.HCM đăng sai địa chỉ tại Đà Nẵng.',
    status: 'resolved',
    resolutionNotes: 'Đã ẩn tin đăng vi phạm và khóa tài khoản người đăng.',
    resolvedBy: 'u-admin-1',
    createdAt: '2026-09-21T09:00:00Z',
    updatedAt: '2026-09-21T11:30:00Z',
  },
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-001',
    userId: 'u-tenant-1',
    title: 'Cảnh báo an toàn Trọ Việt',
    body: 'Tuyệt đối KHÔNG chuyển tiền cọc khi chưa xem phòng và đối chiếu giấy tờ trực tiếp.',
    type: 'anti_scam_warning',
    isRead: false,
    createdAt: '2026-09-24T09:16:00Z',
  },
  {
    id: 'notif-002',
    userId: 'u-tenant-1',
    title: 'Tin nhắn mới từ Cô Lan (Chủ nhà)',
    body: 'Đúng rồi cháu, điện có công tơ riêng từng phòng 3.500đ/kWh...',
    type: 'chat_message',
    isRead: true,
    createdAt: '2026-09-24T08:15:00Z',
  },
  {
    id: 'notif-003',
    userId: 'u-landlord-1',
    title: 'Đánh giá mới cho phòng trọ của bạn',
    body: 'Người thuê Trần Thị Mai đã gửi đánh giá 5 sao cho phòng trọ Nguyễn Du.',
    type: 'review_received',
    isRead: false,
    createdAt: '2026-09-15T10:00:00Z',
  },
];
