/**
 * Trọ Việt - Phase 7 Mock Seed Data
 * Contains realistic Roommate Profiles & Property Handover records for TP. Đà Nẵng.
 * Strict adherence to privacy (display names only) and integer VND currency.
 */

import { RoommateProfile } from '../roommate/matching.js';
import { PropertyHandoverRecord } from '../handover/checklist.js';

export const MOCK_ROOMMATE_PROFILES: RoommateProfile[] = [
  {
    id: 'roommate-dn-001',
    userId: 'user-tenant-01',
    displayName: 'Minh Khang',
    gender: 'male',
    age: 21,
    occupation: 'Sinh viên CNTT ĐH Bách Khoa ĐN',
    budgetMonthlyMax: 1800000,
    targetWards: ['48_HOAKHANHBAC', '48_HOACUONGNAM'],
    sleepSchedule: 'night_owl',
    smokingHabit: 'no_smoking',
    petHabit: 'no_pets',
    cleanlinessLevel: 'moderate',
    genderPreference: 'male_only',
    bio: 'Sinh viên năm 3 chăm chỉ, hay học bài đêm, sống hòa nhã, tôn trọng không gian riêng tư của bạn cùng phòng.',
    hasRoom: false,
    isActive: true,
    createdAt: '2026-09-20T08:00:00Z',
  },
  {
    id: 'roommate-dn-002',
    userId: 'user-student-02',
    displayName: 'Quang Huy',
    gender: 'male',
    age: 22,
    occupation: 'Sinh viên năm cuối ĐH Bách Khoa ĐN',
    budgetMonthlyMax: 1700000,
    targetWards: ['48_HOAKHANHBAC'],
    sleepSchedule: 'night_owl',
    smokingHabit: 'no_smoking',
    petHabit: 'no_pets',
    cleanlinessLevel: 'moderate',
    genderPreference: 'male_only',
    bio: 'Phòng đã có gác lửng kiên cố và máy lạnh, tìm 1 bạn nam ở ghép chia đôi tiền phòng (~1.6tr/người).',
    hasRoom: true,
    existingListingId: 'listing-danang-02',
    existingListingTitle: 'Căn hộ mini ban công thoáng mát gần ĐH Bách Khoa',
    isActive: true,
    createdAt: '2026-09-21T09:30:00Z',
  },
  {
    id: 'roommate-dn-003',
    userId: 'user-worker-01',
    displayName: 'Phương Thảo',
    gender: 'female',
    age: 24,
    occupation: 'Chuyên viên Marketing ven biển Sơn Trà',
    budgetMonthlyMax: 2500000,
    targetWards: ['48_PHUOCMY', '48_HAICHAU1'],
    sleepSchedule: 'early_bird',
    smokingHabit: 'no_smoking',
    petHabit: 'has_cats',
    cleanlinessLevel: 'neat_freak',
    genderPreference: 'female_only',
    bio: 'Đi làm văn phòng giờ hành chính, thích tập yoga và chạy bộ bãi biển. Mình nuôi 1 bé mèo ta rất ngoan và sạch sẽ.',
    hasRoom: false,
    isActive: true,
    createdAt: '2026-09-22T14:15:00Z',
  },
  {
    id: 'roommate-dn-004',
    userId: 'user-worker-02',
    displayName: 'Hồng Ánh',
    gender: 'female',
    age: 23,
    occupation: 'Nhân viên thiết kế đồ họa',
    budgetMonthlyMax: 2600000,
    targetWards: ['48_PHUOCMY', '48_HAICHAU1'],
    sleepSchedule: 'flexible',
    smokingHabit: 'no_smoking',
    petHabit: 'pet_friendly',
    cleanlinessLevel: 'moderate',
    genderPreference: 'female_only',
    bio: 'Thích nghệ thuật, yêu động vật, muốn tìm bạn nữ cùng thuê căn hộ mini view thoáng gần cầu Rồng / Mỹ Khê.',
    hasRoom: false,
    isActive: true,
    createdAt: '2026-09-23T11:00:00Z',
  },
];

export const MOCK_PROPERTY_HANDOVERS: PropertyHandoverRecord[] = [
  {
    id: 'handover-dn-001',
    contractId: 'contract-dn-001',
    listingId: 'listing-danang-01',
    listingTitle: 'Phòng studio cao cấp view sông Hàn',
    landlordId: 'user-landlord-01',
    landlordName: 'Trần Văn An',
    tenantId: 'user-tenant-01',
    tenantName: 'Nguyễn Minh Khang',
    handoverDate: '2026-03-01',
    initialElectricityMeter: 1250,
    electricityMeterPhotoUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136',
    initialWaterMeter: 48,
    waterMeterPhotoUrl: 'https://images.unsplash.com/photo-1584467735871-8e85353a8413',
    itemChecklist: [
      { id: 'h-1', name: 'Chìa khóa phòng & thẻ từ thang máy/cửa cổng', category: 'keys_security', condition: 'good', notes: 'Giao 2 chìa cơ + 1 thẻ từ' },
      { id: 'h-2', name: 'Máy điều hòa & Remote điều khiển', category: 'furniture_appliances', condition: 'good', notes: 'Mát sâu, remote kèm pin mới' },
      { id: 'h-3', name: 'Bình nước nóng lạnh', category: 'furniture_appliances', condition: 'good', notes: 'Hoạt động tốt, có chống giật' },
      { id: 'h-4', name: 'Tủ lạnh & bóng đèn chiếu sáng trong phòng', category: 'furniture_appliances', condition: 'good' },
      { id: 'h-5', name: 'Vòi nước, bồn cầu & thoát sàn vệ sinh không tắc', category: 'infrastructure', condition: 'good' },
      { id: 'h-6', name: 'Cửa sổ, chốt khóa an toàn & tường không thấm mốc', category: 'infrastructure', condition: 'good' },
    ],
    generalNotes: 'Hai bên đã kiểm tra hiện trạng phòng thực tế ngày 01/03/2026. Chỉ số công tơ điện nước được lấy làm mốc tính hóa đơn.',
    landlordConfirmed: true,
    tenantConfirmed: true,
    landlordConfirmedAt: '2026-03-01T09:30:00Z',
    tenantConfirmedAt: '2026-03-01T09:40:00Z',
    status: 'completed',
    createdAt: '2026-03-01T09:00:00Z',
    updatedAt: '2026-03-01T09:40:00Z',
  },
];
